<?

class main{
	private $data=array();
	
	public function __set($name, $value){
		$this->data[$name] = $value;
	}
	
	public function __get($name){
		return $this->data[$name];
	}

	public function __isset($name) {
        return isset($this->data[$name]);
    }
	
	public function __unset($name) {
        unset($this->data[$name]);
    }

/* ############################# metode umum ########################################*/

	public static function date_database_formatting($arr_month, $date){
		$arr_date=preg_split("/ /", $date);
		$month = main::get_array_index($arr_month, $arr_date[1], "value")+1;
		$month = $month < 10 ? "0" . $month : $month;
		return $arr_date[2]."-".$month."-".$arr_date[0];
	}
	
	public static function date_from_jquery_to_string($arr_month, $date){
		$arr_date=explode("/", $date);
		return $arr_date[1]." ".$arr_month[(int)$arr_date[0] ]." ".$arr_date[2];		
	}
	
	public static function formatting_query_string($string){
		$string=str_replace("'", "''", $string);// amankan karakter ' :database
		$string=str_replace("<", "&lt;", $string);// amankan karakter-2 berpotensi xss
		$string=str_replace(">", "&gt;", $string);
		$string=str_replace("&lt;br /&gt;", "<br />", $string);//pulihkan hanya untuk html break
		$string=str_replace("&lt;strong&gt;", "<strong>", $string);$string=str_replace("&lt;/strong&gt;", "</strong>", $string);//pulihkan hanya untuk html strong
		$string=str_replace("&lt;hr width=100% size=1 /&gt;", "<hr width=100% size=1 />", $string);//pulihkan hanya untuk html horizontal line
		//$string=str_replace("=", "&#61;", $string);
		//$string=str_replace("\"", "&quot;", $string);		
		return $string;
	}
	
	public static function formatting_javascript_string($string){
		$string=str_replace("'", "\\'", $string);// amankan karakter ' :javascript
		$string=str_replace("<", "&lt;", $string);// amankan karakter-2 berpotensi xss
		$string=str_replace(">", "&gt;", $string);
		$string=str_replace("&lt;br /&gt;", "<br />", $string);//pulihkan hanya untuk html break
		$string=str_replace("&lt;strong&gt;", "<strong>", $string);$string=str_replace("&lt;/strong&gt;", "</strong>", $string);//pulihkan hanya untuk html strong
		$string=str_replace("&lt;hr width=100% size=1 /&gt;", "<hr width=100% size=1 />", $string);//pulihkan hanya untuk html horizontal line
		//$string=str_replace("=", "&#61;", $string);
		//$string=str_replace("\"", "&quot;", $string);		
		return $string;	
	}
	
	public static function formatting_output_html_string($string){
		$string = str_ireplace("<br />", "\r\n", $string); 
		return $string;
	}
	
	static function __set_option($arr, $opt_selected="", $mode=""){
		$s_option="";
		foreach($arr as $key=>$value){
			$selected="";
			if(!is_array($value)){
				if($mode=="")	{if($opt_selected==$key)$selected="selected";}
				else{if($opt_selected==$value)$selected="selected";}
				if($mode=="")	$s_option.="<option value=\"".$key."\" ".$selected.">".ucwords(strtolower($value))."</option>";
				else $s_option.="<option value=\"".$value."\"".$selected.">".ucwords(strtolower($value))."</option>";
			}else{				
				foreach($value as $key1=>$value1){
					$selected="";
					if($mode=="")	{if($opt_selected==$key1)$selected="selected";}
					else{if($opt_selected==$value1)$selected="selected";}
					
					if($mode=="")	$s_option.="<option value=\"".$key1."\" ".$selected.">".ucwords(strtolower($value1))."</option>";
					else $s_option.="<option value=\"".$value1."\"".$selected.">".ucwords(strtolower($value1))."</option>";
				}
			}
		}
		return $s_option;
	}
	
	public static function reload_page($arr_request,$url="", $target="_self"){
		echo "<html><body onload=\"javascript:form1.submit()\">";
		echo "<form name=\"form1\" id=\"form1\" method=\"post\" action=\"".$url."\" target=\"". $target ."\">";
		foreach($arr_request as $key=>$value)
			echo "<input type=\"hidden\" name=\"".$key."\" id=\"".$key."\" value=\"".$value."\" />";
		echo "</form>";
		echo "</body></html>";
	}
	
	static function generate_html_form($arr_par=array(),$action=""){
		$return="<html><body onload=\"javascript:document.forms[0].submit()\">
			<form name=\"form1\" id=\"form1\" action=\"$action\" method=\"post\">";
		foreach($arr_par as $key=>$value)	
			if(!is_array($value))
				$return.="<input type=\"hidden\" name=\"$key\" id=\"$key\" value=\"$value\" />";
			else	foreach($value as $key1=>$value1)
				$return.="<input type=\"hidden\" name=\"".$key."[".$key1."]"."\" id=\"".$key."[".$key1."]"."\" value=\"$value1\" />";
		$return.="</form></body></html>";
		return $return;
	}

	static function number_format_dec( $number ){
		$desimal = 0;
		if( $number < 100 ) $desimal = 2;
		return number_format( $number, $desimal );
	}


/* ajax */	
	static function __callback(
		$callback = "", 
		$msg = "", 
		$is_direct = false /*false : diparsing dulu ke js function generated by fungsi dibawah, sblm ditampilin ke user; true : langsung ditampilin ke user*/
	){
		if(!$is_direct){
			if($callback == "") throw new Exception('js callback function not set!');
			$tinybox = "TINY.box.show({image:'". __DIR__ ."/../images/loading.gif',boxid:'',width:33,height:33,fixed:true,maskid:'greymask',maskopacity:40,close:false});";
			$return = "<script>try{window.onload=function(){". $tinybox . $callback .";callback('". $msg ."');}}catch(err){alert(err)}</script>";
		}else	$return = $msg;
		return $return;
	}
	
	static function initiating_callback($obj, $msg){
		$cb = "callback";
		if(@$_REQUEST[$cb] != ""){						
			$obj->view->assign($cb, self::__callback($_REQUEST[$cb], $msg));
			$obj->view->display('loading_view');
		}else	echo self::__callback("", $msg, true);
	}
	
// ##############################################################################################



/*
fungsi send email error
*/
	public static function send_email($target=SUPPORT_EMAIL,$subject="",$content="", $lampiran=array()){
		$message=file_get_contents(EMAIL_TEMPLATE);	

		$message=str_replace("#greetingname#", $target, $message);
		$message=str_replace("#content#", $content, $message);
		$message=str_replace("#lang_email_info_en#", "", $message);
		$message=str_replace("#lang_email_footer#", "", $message);
		$message=str_replace("#horizontal_line#", "<hr width=100% size=1 />", $message);

		ini_set("include_path",INCLUDE_PATH);
		require_once "pear/class.smtp.php";
		require_once "pear/PHPMailer.php";		
		
		$phpmailer = new PHPMailer();
		$phpmailer->SMTPDebug=false;
		$phpmailer->Debugoutput="html";
		$phpmailer->Host=SMTP_HOST;
		$phpmailer->Port=SMTP_PORT;
		$phpmailer->SMTPSecure="tls";
		$phpmailer->SMTPAuth=SMTP_AUTH;
		$phpmailer->Username=SMTP_USERNAME;
		$phpmailer->Password=SMTP_PASSWORD;
		$phpmailer->Mailer="smtp";
		$phpmailer->SMTPOptions=array(
			'ssl' => array(
				'verify_peer' => false,
				'verify_peer_name' => false,
				'allow_self_signed' => true
			)
		);

		$phpmailer->SetFrom(SUPPORT_EMAIL, SUPPORT_EMAIL);
		$phpmailer->Subject = $subject;
		$phpmailer->MsgHTML($message);

		$arr_target = explode(",", $target);
		foreach ($arr_target as $email) 	$phpmailer->AddAddress( trim($email) );

		$phpmailer->AddBCC(SUPPORT_EMAIL);

		if( EMAIL_DIAKTIFKAN )
			$phpmailer->Send() or die( $phpmailer->ErrorInfo );
		else{
			echo "Recipeints : (To) " . $target . "<br />Subject : " . $subject . "<br />" . $message;
			return;
		}
		
		restore_include_path();
	}
	
	// buat sambungan ke satrio
	static function buat_sambungan_ke_satrio($arr_par, $source = ""){
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_URL, $GLOBALS["web_servis_url"]);
			curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
			curl_setopt($ch, CURLOPT_POST, true);
			curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($arr_par));
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			
			curl_setopt($ch, CURLOPT_CONNECTTIMEOUT , $GLOBALS["curl_connection_timeout"]); 
			curl_setopt($ch, CURLOPT_TIMEOUT, $GLOBALS["curl_timeout"]); 
			
			$server_output = curl_exec ($ch);

			$curl_error = curl_errno($ch);
			if($curl_error != 0)
				main::send_email(SUPPORT_EMAIL, 
					"[mobile sales] :: Error ". $source ." dari ACCPAC", 
					"Mas bro, 
					tolong segera dicek ada error <strong>". $source ." dari ACCPAC</strong>.<br />
					Lokasinya di web mobile sales<br />
					Kode errornya adalah : " . $curl_error);
			
			curl_close ($ch);
			return $server_output;
	}
}
?>